#!/bin/bash
#
# @(#) writes a quick makefile for remaking the executable in the current 
# @(#) directory
#
if [ $# != 1 ]; then
   echo Usage: $0 nD
else
   echo '#'
   echo '#--Makefile to remake the executable and copy to this directory'
   echo '#  Generated by '$0':' `date`
   echo '#'
   echo default':'$1
   echo '#NDSPMHD_DIR='${0/scripts\/writemake.sh/};
   echo
   echo '3D: checkdir'
   echo '	cd ${NDSPMHD_DIR}; make 3D; cd -; cp ~/ndspmhd/3DSPMHD .'
   echo '2D: checkdir'
   echo '	cd ${NDSPMHD_DIR}; make 2D; cd -; cp ~/ndspmhd/2DSPMHD .'
   echo '1D: checkdir'
   echo '	cd ${NDSPMHD_DIR}; make 1D; cd -; cp ~/ndspmhd/1DSPMHD .'
   echo 'edit: checkdir'
   echo '	cd ${NDSPMHD_DIR}; make edit'$1
   echo 'moddump: checkdir'
   echo '	cd ${NDSPMHD_DIR}/src; make moddump'$1
   echo 'moddumpc: checkdir'
   echo '	cd ${NDSPMHD_DIR}/src; make clean; make moddump'$1
   echo 'make: checkdir'
   echo '	cd ${NDSPMHD_DIR}/src; nedit Makefile &'
   echo 'clean: checkdir'
   echo '	cd ${NDSPMHD_DIR}; make clean'
   echo 'checkdir:'
   echo 'ifndef NDSPMHD_DIR'
   echo '	@echo "ERROR: need NDSPMHD_DIR set to location of ndspmhd code"'
   echo '	@echo "       e.g. export NDSPMHD_DIR=~/ndspmhd"'
   echo '	@quit'
   echo 'endif'
 fi
