#!/bin/bash
#
# @(#) writes a quick makefile for remaking the executable in the current 
# @(#) directory
#
if [ $# != 1 ]; then
   echo Usage: $0 nD
else
   echo '#'
   echo '#--Makefile to remake the executable and copy to this directory'
   echo '#  Generated by '$0':' `date`
   echo '#'
   echo default':'$1
   echo 'CODEDIR='${0/scripts\/writemake.sh/};
   echo
   echo '3D:'
   echo '	cd ${CODEDIR}; make 3D; cd -; cp ~/ndspmhd/3DSPMHD .'
   echo '2D:'
   echo '	cd ${CODEDIR}; make 2D; cd -; cp ~/ndspmhd/2DSPMHD .'
   echo '1D:'
   echo '	cd ${CODEDIR}; make 1D; cd -; cp ~/ndspmhd/1DSPMHD .'
   echo 'edit:'
   echo '	cd ${CODEDIR}; make edit'$1
   echo 'moddump:'
   echo '	cd ${CODEDIR}/src; make moddump'$1
   echo 'moddumpc:'
   echo '	cd ${CODEDIR}/src; make clean; make moddump'$1
   echo 'make:'
   echo '	cd ${CODEDIR}/src; nedit Makefile &'
   echo 'clean:'
   echo '	cd ${CODEDIR}; make clean'
fi
