#!/usr/bin/tcsh
#
# @(#) stuff to run jobs in the background
# type:
#
# qsub multirun
#
# to submit job to the Sun Grid Engine (SGE)

#
# I want to run my job in tcsh:
#$ -S /usr/bin/tcsh
#
# run the job in the directory qsub was run from rather than the home directory
#$ -cwd 
#
# Mail me if the job is aborted or at the end of job:
#$ -M dprice@ast.cam.ac.uk
#$ -m ae
#
# put the output from this job in:
#$ -o ~/ndspmhd/multirun.output
#
# should there be any errors, put them in:
#$ -e ~/ndspmhd/multirun.errors
#
# set maximum memory usage
#$ -l s_vmem=20M
#$ -l h_vmem=20M
#
# name the job
#
#$ -N multirun
#
# run my cpu-intensive job:

~/ndspmhd/1DSPMHD multirun
